// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXmMq8VmY7gE7Np7llsgwcLNqWusRmuIU',
    appId: '1:247931870466:android:40f4a9d9b2fde710d6b61b',
    messagingSenderId: '247931870466',
    projectId: 'my-app-chat-1db1b',
    storageBucket: 'my-app-chat-1db1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNIYBUKAOBqg9dZzZqcNdoElJ-YF_c18',
    appId: '1:247931870466:ios:0e08ec019168c5bed6b61b',
    messagingSenderId: '247931870466',
    projectId: 'my-app-chat-1db1b',
    storageBucket: 'my-app-chat-1db1b.appspot.com',
    androidClientId: '247931870466-ad2g5230879uk7ploq7gms3nvqso4mjh.apps.googleusercontent.com',
    iosClientId: '247931870466-dmkoqsju5p87snvqerd1ps51oiekse07.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatApp',
  );
}
